version: "3.7"

services:
  highload_pg:
    image: postgres:14
    container_name: highload_pg
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: highload
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./postgres/db:/var/lib/postgresql/data

  eureka-server:
    image: aixoxs/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    expose:
      - "8761"
    environment:
      SERVER_PORT: 8761

  config-server:
    image: aixoxs/config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      SERVER_PORT: 8888
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
    depends_on:
      - eureka-server

  gateway_service:
    image: aixoxs/gateway-service:latest
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      CONFIG_HOST: config-server
      CONFIG_PORT: 8888
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
      - config-server

  auth-facade:
    image: aixoxs/auth-facade:latest
    container_name: auth-facade
    ports:
      - "8086:8086"
    environment:
      SERVER_PORT: 8086
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
      - config-server

  auth-reactive-facade:
    image: aixoxs/auth-reactive-facade:latest
    container_name: auth-reactive-facade
    ports:
      - "8087:8087"
    environment:
      SERVER_PORT: 8087
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
      - config-server

  user-service:
    image: aixoxs/user-service:latest
    container_name: user-service
    ports:
      - "8084:8084"
    environment:
      SERVER_PORT: 8084
      CONFIG_HOST: config-server
      CONFIG_PORT: 8888
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      spring.r2dbc.url: r2dbc:postgresql://highload_pg/highload?currentSchema=user_info
      spring.liquibase.url: jdbc:postgresql://highload_pg:5433/highload?currentSchema=user_info
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
      - config-server
      - highload_pg
