server:
  port: ${SERVER_PORT:8080}

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://${CONFIG_HOST:localhost}:${CONFIG_PORT:8888}