server:
  port: ${SERVER_PORT:8084}

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://${CONFIG_HOST:localhost}:${CONFIG_PORT:8888}

#3
#management:
#  endpoints:
#    web:
#      exposure:
#        include: prometheus,health,info,metrics
#  metrics:
#    enable:
#      jvm: true
#    export:
#      prometheus:
#        enabled: true
#        pushgateway:
#          enabled: true
#          push-rate: 5s
#          base-url: 192.168.123.148:9091
#          grouping-key:
#            application: ${spring.application.name}
#            instance: ${spring.application.name}:${server.port}
#    distribution:
#      percentiles-histogram:
#        "[http.server.requests]": true
#    tags:
#      application: ${spring.application.name}
