/*CREATE SCHEMA IF NOT EXISTS USER_INFO;*/
CREATE TABLE IF NOT EXISTS ROLES
(
    ID   UUID PRIMARY KEY,
    NAME VARCHAR(16) NOT NULL UNIQUE CHECK (NAME != '')
);

CREATE TABLE IF NOT EXISTS USERS
(
    ID       UUID PRIMARY KEY,
    USERNAME    VARCHAR(20)  NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE_ID  UUID REFERENCES ROLES (ID) ON DELETE SET NULL ON UPDATE CASCADE,
    CHECK ((USERNAME != '') AND (PASSWORD != ''))
);