version: '3.x'
volumes:
  jenkins_home:
services:
  jenkins:
    image: jenkins-docker
    build:
      context: .
    ports:
      - "9091:8080"
      - "9092:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
