spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
          lower-case-service-id: true
server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true